# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=40)),
                ('mobile_no', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2016, 7, 17, 17, 49, 54, 421858, tzinfo=utc))),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=datetime.datetime(2016, 7, 17, 17, 49, 54, 423806, tzinfo=utc))),
                ('last_update_date', models.DateField(default=datetime.datetime(2016, 7, 17, 17, 49, 54, 423876, tzinfo=utc))),
                ('draft_staus', models.BooleanField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
