# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=40)),
                ('mobile_no', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2016, 7, 16, 18, 4, 48, 500479, tzinfo=utc))),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
            ],
        ),
    ]
