# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 7, 17, 17, 56, 47, 431672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_update_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 17, 17, 56, 47, 432866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 17, 56, 47, 432818, tzinfo=utc)),
        ),
    ]
