# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20160716_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 7, 16, 18, 24, 43, 239258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_update_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 16, 18, 24, 43, 240412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 18, 24, 43, 240367, tzinfo=utc)),
        ),
    ]
