# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20160716_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 7, 16, 18, 26, 4, 787131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_update_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 16, 18, 26, 4, 788276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 18, 26, 4, 788236, tzinfo=utc)),
        ),
    ]
