# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20160716_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='staus',
            new_name='draft_staus',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 7, 16, 18, 29, 42, 186731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_update_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 16, 18, 29, 42, 188577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 18, 29, 42, 188469, tzinfo=utc)),
        ),
    ]
