# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20160717_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 7, 17, 14, 2, 55, 926959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_update_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 17, 14, 2, 55, 928046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 14, 2, 55, 928009, tzinfo=utc)),
        ),
    ]
